server:
  port: 10000

spring:
  application:
    name: bca-svc-business

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

logging:
  level:
    root: info
    com.beyond.cloud.alibaba: debug
