spring:
  cloud:
    nacos:
#      server-addr: ${LINUX_HOST:192.168.178.129}:8848
      server-addr: nacos-headless.beyond.svc.cluster.local
      discovery:
        namespace: public
        cluster-name: ${spring.application.name}

    alibaba:
      seata:
        tx-service-group: my_test_tx_group

seata:
  enabled: true
  enable-auto-data-source-proxy: true              # 开启数据库自动代理
  registry:
    type: nacos
    nacos:
      server-addr: nacos-headless.beyond.svc.cluster.local
      namespace: public
      cluster: seata-server
      group: DEFAULT_GROUP
  config:
    type: nacos
    nacos:
      server-addr: nacos-headless.beyond.svc.cluster.local
      namespace: public

management:
  endpoints:
    web:
      exposure:
        include: '*'

