spring:
  cloud:
    nacos:
      server-addr: ${LINUX_HOST:192.168.110.179}:8848
      discovery:
        namespace: public
        cluster-name: ${spring.application.name}
        ip: ${LOCAL_HOST:192.168.110.179}

    alibaba:
      seata:
        tx-service-group: my_test_tx_group

seata:
  enabled: true
  enable-auto-data-source-proxy: true              # 开启数据库自动代理

management:
  endpoints:
    web:
      exposure:
        include: '*'

