package com.beyond.cloud.alibaba.account.mapper;

import com.beyond.cloud.alibaba.account.domain.entity.PayRecord;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int insert(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int insertSelective(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    PayRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyVersioned(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bca_pay_record
     *
     * @mbg.generated
     */
    int updateVersionedSelective(PayRecord record);
}